name: make all

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  makeall:
    name: make all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: install deps
        run: |
          sudo apt install -y \
            libseccomp-dev \
            parallel \
            uidmap \
            pigz \
            --no-install-recommends
        shell: bash
      - uses: actions/setup-go@v2
        with:
          go-version: "^1.13.1" # The Go version to download (if necessary) and use.
      - name: install go tools
        run: |
          go get golang.org/x/lint/golint
          go get honnef.co/go/tools/cmd/staticcheck
          go get -u github.com/go-bindata/go-bindata/go-bindata
          sudo mkdir -p /run/runc
          sudo chown runner:runner -R /run/runc
        shell: bash
      - name: make all
        run: make all
        shell: bash
      - name: Run Test Coverage
        run: |
          make cover
          bash <(curl -s https://codecov.io/bash)
        shell: bash
      - name: Run e2e Tests
        run: |
          make install
          ./contrib/e2e-dockerfiles-build-test.sh
        env:
          STATE_DIR: $HOME/img
